import type { Express } from "express";

import route1 from "./routes/agent";
import route2 from "./routes/agent/answer";
import route3 from "./routes/agent/canvasResult";
import route4 from "./routes/agent/create";
import route5 from "./routes/agent/get";
import route6 from "./routes/agent/list";
import route7 from "./routes/agent/mentionSource";
import route8 from "./routes/agent/message";
import route9 from "./routes/agent/rename";
import route10 from "./routes/agent/skills";
import route11 from "./routes/agents/a2a/get";
import route12 from "./routes/agents/a2a/save";
import route13 from "./routes/agents/connect";
import route14 from "./routes/agents/get";
import route15 from "./routes/agents/install";
import route16 from "./routes/agents/read";
import route17 from "./routes/agents/save";
import route18 from "./routes/agents/setEnabled";
import route19 from "./routes/agents/uninstall";
import route20 from "./routes/ai/generate";
import route21 from "./routes/ai/media/generate";
import route22 from "./routes/ai/media/models";
import route23 from "./routes/ai/models";
import route24 from "./routes/assets/library/create";
import route25 from "./routes/assets/library/list";
import route26 from "./routes/assets/library/read";
import route27 from "./routes/assets/library/remove";
import route28 from "./routes/assets/library/update";
import route29 from "./routes/assets/library/upload";
import route30 from "./routes/assets/list";
import route31 from "./routes/assets/mkdir";
import route32 from "./routes/assets/read";
import route33 from "./routes/assets/remove";
import route34 from "./routes/assets/rename";
import route35 from "./routes/assets/save";
import route36 from "./routes/auth/code";
import route37 from "./routes/auth/login";
import route38 from "./routes/auth/logout";
import route39 from "./routes/auth/me";
import route40 from "./routes/desktop/clipboard/read";
import route41 from "./routes/desktop/clipboard/write";
import route42 from "./routes/desktop/devtools";
import route43 from "./routes/desktop/openUrl";
import route44 from "./routes/desktop/plugins/install";
import route45 from "./routes/desktop/providerFile/read";
import route46 from "./routes/desktop/providerFile/select";
import route47 from "./routes/desktop/ready";
import route48 from "./routes/desktop/saveFile";
import route49 from "./routes/desktop/selectDirectory";
import route50 from "./routes/desktop/selectSaveFile";
import route51 from "./routes/desktop/update/apply";
import route52 from "./routes/desktop/update/check";
import route53 from "./routes/desktop/update/download";
import route54 from "./routes/desktop/update/index";
import route55 from "./routes/ffmpeg/cancel";
import route56 from "./routes/ffmpeg/download";
import route57 from "./routes/ffmpeg/events";
import route58 from "./routes/ffmpeg/execute";
import route59 from "./routes/ffmpeg/progress";
import route60 from "./routes/ffmpeg/status";
import route61 from "./routes/mcp/control/events";
import route62 from "./routes/mcp/control/result";
import route63 from "./routes/mcp/control/state";
import route64 from "./routes/mcp/skill";
import route65 from "./routes/mcp/status";
import route66 from "./routes/nodes/files";
import route67 from "./routes/nodes/get";
import route68 from "./routes/nodes/install";
import route69 from "./routes/nodes/save";
import route70 from "./routes/nodes/setEnabled";
import route71 from "./routes/nodes/uninstall";
import route72 from "./routes/plugins/export";
import route73 from "./routes/profile/keys/get";
import route74 from "./routes/profile/keys/save";
import route75 from "./routes/projects/list";
import route76 from "./routes/projects/remove";
import route77 from "./routes/projects/rename";
import route78 from "./routes/projects/upsert";
import route79 from "./routes/providers/debug/inspect";
import route80 from "./routes/providers/debug/run";
import route81 from "./routes/providers/media/add";
import route82 from "./routes/providers/media/delete";
import route83 from "./routes/providers/media/list";
import route84 from "./routes/providers/media/models";
import route85 from "./routes/providers/media/save";
import route86 from "./routes/providers/models";
import route87 from "./routes/settings/get";
import route88 from "./routes/settings/personalization/get";
import route89 from "./routes/settings/personalization/save";
import route90 from "./routes/settings/save";
import route91 from "./routes/settings/systemPrompt";
import route92 from "./routes/skills/create";
import route93 from "./routes/skills/get";
import route94 from "./routes/skills/install";
import route95 from "./routes/skills/list";
import route96 from "./routes/skills/move";
import route97 from "./routes/skills/order";
import route98 from "./routes/skills/read";
import route99 from "./routes/skills/save";
import route100 from "./routes/skills/uninstall";
import route101 from "./routes/tools/client";
import route102 from "./routes/tools/get";
import route103 from "./routes/tools/install";
import route104 from "./routes/tools/renderers";
import route105 from "./routes/tools/save";
import route106 from "./routes/tools/setEnabled";
import route107 from "./routes/tools/uninstall";
import route108 from "./routes/users/create";
import route109 from "./routes/users/list";
import route110 from "./routes/users/remove";
import route111 from "./routes/users/update";
import route112 from "./routes/workspaces/check";
import route113 from "./routes/workspaces/files/list";
import route114 from "./routes/workspaces/files/mkdir";
import route115 from "./routes/workspaces/files/read";
import route116 from "./routes/workspaces/files/remove";
import route117 from "./routes/workspaces/files/rename";
import route118 from "./routes/workspaces/files/write";
import route119 from "./routes/workspaces/list";
import route120 from "./routes/workspaces/selectDirectory";

export default (app: Express) => {
  app.use("/api/agent", route1);
  app.use("/api/agent/answer", route2);
  app.use("/api/agent/canvasResult", route3);
  app.use("/api/agent/create", route4);
  app.use("/api/agent/get", route5);
  app.use("/api/agent/list", route6);
  app.use("/api/agent/mentionSource", route7);
  app.use("/api/agent/message", route8);
  app.use("/api/agent/rename", route9);
  app.use("/api/agent/skills", route10);
  app.use("/api/agents/a2a/get", route11);
  app.use("/api/agents/a2a/save", route12);
  app.use("/api/agents/connect", route13);
  app.use("/api/agents/get", route14);
  app.use("/api/agents/install", route15);
  app.use("/api/agents/read", route16);
  app.use("/api/agents/save", route17);
  app.use("/api/agents/setEnabled", route18);
  app.use("/api/agents/uninstall", route19);
  app.use("/api/ai/generate", route20);
  app.use("/api/ai/media/generate", route21);
  app.use("/api/ai/media/models", route22);
  app.use("/api/ai/models", route23);
  app.use("/api/assets/library/create", route24);
  app.use("/api/assets/library/list", route25);
  app.use("/api/assets/library/read", route26);
  app.use("/api/assets/library/remove", route27);
  app.use("/api/assets/library/update", route28);
  app.use("/api/assets/library/upload", route29);
  app.use("/api/assets/list", route30);
  app.use("/api/assets/mkdir", route31);
  app.use("/api/assets/read", route32);
  app.use("/api/assets/remove", route33);
  app.use("/api/assets/rename", route34);
  app.use("/api/assets/save", route35);
  app.use("/api/auth/code", route36);
  app.use("/api/auth/login", route37);
  app.use("/api/auth/logout", route38);
  app.use("/api/auth/me", route39);
  app.use("/api/desktop/clipboard/read", route40);
  app.use("/api/desktop/clipboard/write", route41);
  app.use("/api/desktop/devtools", route42);
  app.use("/api/desktop/openUrl", route43);
  app.use("/api/desktop/plugins/install", route44);
  app.use("/api/desktop/providerFile/read", route45);
  app.use("/api/desktop/providerFile/select", route46);
  app.use("/api/desktop/ready", route47);
  app.use("/api/desktop/saveFile", route48);
  app.use("/api/desktop/selectDirectory", route49);
  app.use("/api/desktop/selectSaveFile", route50);
  app.use("/api/desktop/update/apply", route51);
  app.use("/api/desktop/update/check", route52);
  app.use("/api/desktop/update/download", route53);
  app.use("/api/desktop/update", route54);
  app.use("/api/ffmpeg/cancel", route55);
  app.use("/api/ffmpeg/download", route56);
  app.use("/api/ffmpeg/events", route57);
  app.use("/api/ffmpeg/execute", route58);
  app.use("/api/ffmpeg/progress", route59);
  app.use("/api/ffmpeg/status", route60);
  app.use("/api/mcp/control/events", route61);
  app.use("/api/mcp/control/result", route62);
  app.use("/api/mcp/control/state", route63);
  app.use("/api/mcp/skill", route64);
  app.use("/api/mcp/status", route65);
  app.use("/api/nodes/files", route66);
  app.use("/api/nodes/get", route67);
  app.use("/api/nodes/install", route68);
  app.use("/api/nodes/save", route69);
  app.use("/api/nodes/setEnabled", route70);
  app.use("/api/nodes/uninstall", route71);
  app.use("/api/plugins/export", route72);
  app.use("/api/profile/keys/get", route73);
  app.use("/api/profile/keys/save", route74);
  app.use("/api/projects/list", route75);
  app.use("/api/projects/remove", route76);
  app.use("/api/projects/rename", route77);
  app.use("/api/projects/upsert", route78);
  app.use("/api/providers/debug/inspect", route79);
  app.use("/api/providers/debug/run", route80);
  app.use("/api/providers/media/add", route81);
  app.use("/api/providers/media/delete", route82);
  app.use("/api/providers/media/list", route83);
  app.use("/api/providers/media/models", route84);
  app.use("/api/providers/media/save", route85);
  app.use("/api/providers/models", route86);
  app.use("/api/settings/get", route87);
  app.use("/api/settings/personalization/get", route88);
  app.use("/api/settings/personalization/save", route89);
  app.use("/api/settings/save", route90);
  app.use("/api/settings/systemPrompt", route91);
  app.use("/api/skills/create", route92);
  app.use("/api/skills/get", route93);
  app.use("/api/skills/install", route94);
  app.use("/api/skills/list", route95);
  app.use("/api/skills/move", route96);
  app.use("/api/skills/order", route97);
  app.use("/api/skills/read", route98);
  app.use("/api/skills/save", route99);
  app.use("/api/skills/uninstall", route100);
  app.use("/api/tools/client", route101);
  app.use("/api/tools/get", route102);
  app.use("/api/tools/install", route103);
  app.use("/api/tools/renderers", route104);
  app.use("/api/tools/save", route105);
  app.use("/api/tools/setEnabled", route106);
  app.use("/api/tools/uninstall", route107);
  app.use("/api/users/create", route108);
  app.use("/api/users/list", route109);
  app.use("/api/users/remove", route110);
  app.use("/api/users/update", route111);
  app.use("/api/workspaces/check", route112);
  app.use("/api/workspaces/files/list", route113);
  app.use("/api/workspaces/files/mkdir", route114);
  app.use("/api/workspaces/files/read", route115);
  app.use("/api/workspaces/files/remove", route116);
  app.use("/api/workspaces/files/rename", route117);
  app.use("/api/workspaces/files/write", route118);
  app.use("/api/workspaces/list", route119);
  app.use("/api/workspaces/selectDirectory", route120);
}
